#!/bin/bash

# Get the directory of the running instnace
InstanceDirectory=$(cd "$(dirname "$0")" && pwd)

# Get the project directory of script
ProjectDirectory=$( dirname $(realpath $InstanceDirectory/spstic) )

# Link the file if not already done
if [ ! -L "/bin/spstic" ]; then
  echo -e "\x1b[2m    We're attempting to link static to your user shell (sudo is required).\x1b[0m"
  echo -e "\x1b[2m    Please enter your password when required\x1b[0m"
  echo -e ""
  sleep 1
  sudo ln -s $ProjectDirectory/spstic /bin/spstic
  sudo ln -s /bin/spstic /bin/spastic
  sudo ln -s /bin/spstic /bin/static
  echo ""
fi

# Create the config files if not already done
if [ ! -f "$ProjectDirectory/config/config.js" ]; then

# Create the config folder
mkdir -p $ProjectDirectory/config

# Write the config
cat <<EOF > $ProjectDirectory/config/config.js
export const ProjectDirectory = '$ProjectDirectory';
export const CertbotDirectory = '$ProjectDirectory/certbot';
export const ConfigDirectory = '$ProjectDirectory/config';
export const ScriptsDirectory = '$ProjectDirectory/scripts';
export * from './credentials.js';
EOF

fi
# Create the ccredentials files if not already done
if [ ! -f "$ProjectDirectory/config/credentials.js" ]; then

# Write the credentials (blank)
cat <<EOF > $ProjectDirectory/config/credentials.js
export const WildcardDomain = '';
export const BaseDomain = '';
export const CloudflareAPIToken = '';
export const NgrokAuthtoken = '';
export const NgrokAPIKey = '';
EOF

fi

# Handle help
if [[ $1 == "--help" ]]; then
  echo ""
  echo -e "\x1b[34m  \x1b[4m\x1b[1mspstic\x1b[0m"
  echo ""
  echo -e "\x1b[34m\x1b[2m    A static service tool using Deno (esbuild & live-reloading), Ngrok, Certbot and Cloudflare\x1b[0m"
  echo ""
  echo -e "\x1b[34m\x1b[2m    * Deno is used to create a static file server (including esbuild & live-reloading)\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Ngrok is used to tunnel this server to any specified domain\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Certbot is used to issue a TLS/SSL certificate for the specified domain\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Cloudflare is used for DNS service\x1b[0m"
  echo ""
  echo -e "\x1b[2m\x1b[1m    --subdomain=[subdomain]\x1b[0m"
  echo -e "\x1b[2m      Deploy a static service from this directory on the specfied subdomain (e.g. xyz123)\x1b[0m"
  echo ""
  echo -e "\x1b[2m\x1b[1m    --port=[port]\x1b[0m"
  echo -e "\x1b[2m      Deploy a static service from this directory on the specfied port (e.g. 8080)\x1b[0m"
  echo ""
  echo -e "\x1b[2m\x1b[1m    --local\x1b[0m"
  echo -e "\x1b[2m      Deploy a static service from this directory without Certbot or Ngrok\x1b[0m"
  echo ""
  echo -e "\x1b[2m\x1b[1m    --configure\x1b[0m"
  echo -e "\x1b[2m      Configure the credentials\x1b[0m"
  echo ""
  echo -e "\x1b[2m\x1b[1m    --help\x1b[0m"
  echo -e "\x1b[2m      Display this message\x1b[0m"
  echo ""

# Handle reconfigure
elif [[ $1 == "--configure" ]]; then

  echo ""
  echo -e "\x1b[34m  \x1b[4m\x1b[1mspstic\x1b[0m"
  echo ""
  echo -e "\x1b[34m\x1b[2m    A static service tool using Deno, Ngrok, Certbot and Cloudflare\x1b[0m"
  echo ""
  echo -e "\x1b[34m\x1b[2m    * Deno is used to create a static file server (including live-reloading)\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Ngrok is used to tunnel this server to any specified domain\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Certbot is used to issue a TLS/SSL certificate for the specified domain\x1b[0m"
  echo -e "\x1b[34m\x1b[2m    * Cloudflare is used for DNS service\x1b[0m"
  echo ""

  # Request the Wildcard Domain
  echo -e "\x1b[2m    To get started, we need a wildcard domain name that all your services will be deployed to.\x1b[0m"
  echo -e "\x1b[2m    If for example your domain is *.example.io then an example service may be deployed to xyz123.example.io.\x1b[0m"
  echo -e "\x1b[2m    Please enter the wildcard domain you wish to use\x1b[0m"
  echo ""
  read -p "    Wildcard Domain: *." BaseDomain
  echo ""

  # Request the Cloudflare API Token
  echo -e "\x1b[2m    In order to use TLS/SSL for your domain, we need to be able to create a DNS record on your Cloudflare Account.\x1b[0m"
  echo -e "\x1b[2m    Please enter a Cloudflare API Token with access to DNS on the Zone you're wishing to use\x1b[0m"
  echo ""
  read -p "    Cloudflare API Token: " CloudflareAPIToken
  echo ""

  # Request the Ngrok Authtoken
  echo -e "\x1b[2m    Now for Ngrok we need an Authtoken for your local Ngrok tunelling instance.\x1b[0m"
  echo -e "\x1b[2m    Please enter your Ngrok Authtoken"
  echo ""
  read -p "    Ngrok Authtoken: " NgrokAuthtoken
  echo ""

  # Request the Ngrok API Key
  echo -e "\x1b[2m    Finally, we need an Ngork API Key to upload your TLS/SSL certificates.\x1b[0m"
  echo -e "\x1b[2m    Please enter your Ngrok API Key\x1b[0m"
  echo ""
  read -p "    Ngrok API Key: " NgrokAPIKey
  echo ""

  # Log out the success
  echo -e "\x1b[2m    Congrats, you're all setup and ready to run \x1b[1mspstic\x1b[0m\x1b[2m from your terminal\x1b[0m"
  echo ""
  echo -e "\x1b[2m      \x1b[4msee:\x1b[0m\x1b[2m\x1b[1m spstic \x1b[2m--help\x1b[0m"
  echo ""


# Create the config folder
mkdir -p $ProjectDirectory/config

# Write the directories
cat <<EOF > $ProjectDirectory/config/config.js
export const ProjectDirectory = '$ProjectDirectory';
export const CertbotDirectory = '$ProjectDirectory/certbot';
export const ConfigDirectory = '$ProjectDirectory/config';
export const ScriptsDirectory = '$ProjectDirectory/scripts';
export * from './credentials.js';
EOF

# Write the credentials
cat <<EOF > $ProjectDirectory/config/credentials.js
export const WildcardDomain = '*.$BaseDomain';
export const BaseDomain = '$BaseDomain';
export const CloudflareAPIToken = '$CloudflareAPIToken';
export const NgrokAuthtoken = '$NgrokAuthtoken';
export const NgrokAPIKey = '$NgrokAPIKey';
EOF

# Write the cloudflare credentials
echo "dns_cloudflare_api_token = $CloudflareAPIToken" > $ProjectDirectory/config/cloudflare.ini

# Handle script
else

  # Run with any params
  deno run --allow-all --no-check $ProjectDirectory/scripts/loader.js $1 $2 $3 $4
  fi